#!/bin/bash

while getopts b: OPT ; do
    targetid=$OPTARG
done

currentid=$(tmux display-message -p '#{pane_id}')
tztable=$(tmux showenv | grep tztable | sed "s/^tztable=//")

if [ -n "$targetid" ] ; then
    tmux swap-pane -t $targetid -s $currentid \; \
         setenv tztable "$tztable:$targetid=$currentid"
    echo "******************************"
    echo "**** this is a dummy pane ****"
    echo "******************************"
    stty intr undef
    while : ; do read ; done
elif targets=$(echo $tztable | sed "s/:/\n/g" | tail -n +2 | grep "^$currentid=") ; then
    targetid=$(echo $targets | sed "s/^.*=//" | head -n 1)
    tmux swap-pane -t $targetid -s $currentid \; \
         kill-pane -t $targetid \; \
         setenv tztable "$(echo $tztable | sed "s/:$currentid=[^:]*//")"
else
    tmux new-window "$0 -b $currentid"
fi
